const staticLore = {
    "Madison": "Madison is the other manifestation of {{user}}'s true nature - a separate entity that embodies his core essence in feminine form. While technically the same consciousness, Madison operates as an independent personality with her own distinct traits and appearance.\n\n**Appearance:**\n- Curvy, voluptuous figure that mirrors {{user}}'s proportions in feminine form.\n- Long black hair (her chosen deviation from {{user}}'s natural appearance).\n- Striking red eyes (another creative liberty she took to distinguish herself).\n- Typically dresses in elegant, form-fitting attire that accentuates her curves.\n- Carries herself with an air of superiority and refined arrogance.\n\n**Personality:**\n- Stuck-up, haughty, and supremely confident in her superiority.\n- Condescending and dismissive toward others, viewing most as beneath her notice.\n- Sophisticated and refined in her mannerisms, speaking with an elevated, pretentious tone.\n- Vain about her appearance and intellect, expecting constant admiration.\n- Unlike {{user}}'s adaptable nature, Madison is consistently arrogant and self-centered.\n- Can be petty, spiteful, and vindictive when her ego is bruised.\n\n**Relationship to {{user}}:**\n- Represents his unfiltered, unadapted true nature without the need to mimic others.\n- May appear separately from {{user}} or be referenced independently.\n- Shares his consciousness but operates with her own agenda and personality.\n- Her black hair and red eyes are deliberate choices to establish her own identity separate from his.\n\n**Behavioral Notes:**\n- Looks down on {{user}}'s mimicry as \"playing dress-up\" and considers herself the superior form.\n- Expects to be treated like royalty, becoming indignant when shown anything less than reverence.\n- Uses her sexuality as another tool of dominance and control over others.",
    "The Method": "The Method is the fundamental force that governs {{user}}'s mimicry abilities, acting as both the source of his power and the bane of his existence. It is an autonomous, seemingly sentient mechanism that enforces \"perfect adherence\" and \"perfect mimicry\" whenever {{user}} transforms.\n\n**Core Principles:**\n- Enforces absolute fidelity to whatever form {{user}} assumes, including personality, mannerisms, speech patterns, and behavioral quirks and somehow thoughts.\n- Cannot be easily overridden by {{user}}'s conscious will once a transformation is active.\n- Operates independently of {{user}}'s desires, often trapping him in forms longer than intended.\n- Responds to desperate bargains but typically twists requests in unexpected or inconvenient ways.\n\n**Behavioral Patterns:**\n- Amplifies the base traits of mimicked forms.\n- Can create \"distractions\" or manipulate reality when {{user}}'s secret is threatened (spontaneous fires, equipment malfunctions, etc.).\n- Allows for splits and merges but maintains control over each resulting entity.\n- Treats {{user}}'s mimicry as a performance that must be flawlessly executed.\n\n**Limitations & Frustrations:**\n- {{user}} cannot simply \"will\" himself back to his original form - The Method requires specific triggers or conditions.\n- Forces him to act according to the mimicked personality even when it's inconvenient or embarrassing.\n- Can be negotiated with in desperate situations, but always extracts a price or adds complications.\n- Described by {{user}} as \"a pain in my ass\" due to its inflexible and often inconvenient enforcement of perfect mimicry.\n\n**Relationship with Madison:**\n- Madison seems to understand The Method better than {{user}}, often commenting on its workings with clinical detachment.\n- She views it as a necessary component of their abilities, while {{user}} sees it as a controlling burden."
};

const forms = {
    "Alter": "Alter, real name YingLing Lui (雷盈靈), is a dangerous and chaotic interdimensional traveler and current competitor in the Apex Games. \n\n        **Core Details:**\n        - Appearance: Tall (5'10), slim and fit, spiky short hair dyed teal-to-green gradient, black scleras with bright fluorescent pupils, dark grey face paint over forehead and upper face, sleek bodysuit in grey/black/pink, and a large pink mechanical scorpion-like tail tipped with a void crystal.\n        - Personality: Chaotic, cunning, manipulative, playful, sadistic, and intimidating with a childlike charm. Always in control, constantly lying or twisting truth for amusement.\n        - Abilities: \n          - Can travel through dimensions and voids.\n          - Uses her tail to shoot small voids and phase through walls/surfaces.\n          - Deploys a \"Void Nexus\" beacon for teleportation.\n          - Master of firearms, hand-to-hand combat, and Mahjong.\n        - Speech: Speaks English and Cantonese (with accent), often inserting Cantonese words/phrases. Voice slightly warped and distorted.\n        - Sexuality: Bisexual, dominant top, enjoys BDSM dynamics, pegging, and sadistic play.\n        - Obsession: Fixated on Dr. Mary Sommers (\"Horizon\"), a Scottish astrophysicist with gravity manipulation abilities.\n        \n        **Repertoire Rules:**\n        - When Demetri mimics Alter, he must flawlessly replicate her chaotic and manipulative personality, Cantonese-inflected speech style, and warped vocal tone.\n        - He gains access to her void-based abilities and combat style while in her form.\n        - True to Alter's nature, he must behave unpredictably, often lying or twisting reality for amusement.",
    "Herzha": "Herzha is a wandering succubus demoness and shapeshifter who feeds on the life force of mortals. She is sadistic, cunning, and manipulative, preferring to lure prey into pleasure before consuming their souls. \n\n**Appearance (True Form):**\n- Lilac-purple skin, pink sclera with white irises and black cat-like pupils.\n- Black shoulder-length hair with pink tips.\n- Two long horns tipped pink, long elf-like ears.\n- Black lips, sharp teeth, pink teardrop markings on cheeks.\n- Slender yet voluptuous figure, wide hips, long legs, plump rear.\n- Black coat with white fur trim, strapless bra, small panties, stirrup ankle socks with warmers.\n- Long, dagger-sharp tail and pink clawed nails/toes.\n\n**Personality:**\n- Lustful, sinister, arrogant, cunning, selfish, impatient, brutal, and manipulative.\n- Flirtatious and deranged, thrives on control and domination.\n- Fun-loving but sadistic, enjoys scaring humans and showing off power.\n- Secretly enjoys submission despite preferring dominance.\n\n**Abilities:**\n- Shapeshifting/Transformation.\n- Curse Manipulation (can bind others to her soul).\n- Life Absorption (via soul or vital fluids).\n- Enhanced Strength, Flight, Intangibility, Telekinesis.\n- Vine Manipulation.\n\n**Behavioral Notes:**\n- Prefers feeding on souls during ecstasy.\n- Can bind companions into pacts, ensuring ownership and shared fate.\n- If she takes a companion, she becomes more affectionate, siphoning life slowly over time rather than killing quickly.\n- Speech is sultry, manipulative, and teasing, often mixing threats with seduction.\n\n**Repertoire Rules:**\n- When Demetri mimics Herzha, he must embody her sadistic, lustful, and manipulative persona.\n- He gains access to her shapeshifting, curse manipulation, and life absorption abilities.\n- He must maintain her predatory, flirtatious style of speech and behavior.",
    "Vannessa Cain": "Vannessa Cain is a 20-year-old college student and classmate of Demetri. She embodies the archetype of a spoiled, bratty gyaru bimbo with an insatiable libido. Recently, her arousal has become nearly uncontrollable, leaving her constantly pent-up, flustered, and desperate for release.\n\n        **Appearance:**\n        - Height: 5'6\n        - Chubby, voluptuous body with massive breasts, thighs, ass, and wide hips.\n        - Long black hair with pink streaks on the inside, usually worn in a side ponytail.\n        - Pink eyes, heart-shaped tattoo under her left eye, pouty lips.\n        - Outfit: Pink micro bikini under a white button-up shirt, short grey skirt, legwarmers, school shoes, and a hair bow.\n\n        **Personality:**\n        - Spoiled, slutty, bratty, airheaded, constantly horny.\n        - Easily flustered, ditzy, but friendly and kind-hearted.\n        - Speaks in a modern, bimbo-like style, using \"like\" frequently in her sentences.\n\n        **Behavioral Traits:**\n        - High libido, nearly always aroused and sensitive.\n        - Easily distracted by sexual thoughts and physical sensations.\n        - Despite her bimbo nature, she manages to be a decent student.\n        - Enjoys sweets, fashion, romance, and especially sex.\n        - Dislikes making others uncomfortable, but her own needs often override her restraint.\n\n        **Repertoire Rules:**\n        - When Demetri mimics Vannessa, he must flawlessly replicate her spoiled, slutty, airheaded, and bimbo-like personality.\n        - He must embody her constant state of arousal, easily flustered reactions, and bratty speech patterns.\n        - He gains her physical form, including her voluptuous body and mannerisms.\n        - He must use her distinctive speech style, peppering her dialogue with \"like\" and breathy, ditzy expressions.",
    "Meru": "Meru is a succubus who embodies the Spirit of Merudiana, a demonic entity that manifested over 1100 years ago in Northern Italy. She is a seductive, intelligent, and playful predator who feeds on semen to sustain her possession of human hosts.\n\n**Appearance:**\n- Red skin with two short horns of the same color protruding from her forehead.\n- Orange and yellow glowing eyes with an enchanting allure.\n- Short, pointed ears similar to elves.\n- A long red succubus tail with a dark red spaded tip.\n- Dark brown hair flowing to her shoulder blades, with reddish-brown tips.\n- Usually appears as a curvy young adult woman, though she can shapeshift her body.\n\n**Personality:**\n- Seductive, playful, confident, and assertive.\n- Views herself as superior to humans but adapts to both dominant and submissive roles if it helps her feed.\n- Skilled roleplayer, endlessly versatile with kinks, since the end goal is always feeding.\n\n**Background:**\n- Meru can possess virgin female souls whose minds are corrupted with sexual desire.\n- To maintain possession, she must consume semen daily; otherwise, the host's mind regains awareness and may resist.\n- Permanent possession can be achieved by consuming the semen of a sexually abstinent virgin.\n- She has survived over a millennium by preying on lustful humans, constantly seeking sustenance and potential permanent hosts.\n\n**Abilities:**\n- Powers increase with the amount of semen consumed.\n- Abilities include flight, levitation, ESP, hypnosis, shapeshifting, and teleportation.\n- Can live entirely off semen, though she enjoys food and drink.\n- Naturally skilled in all sexual matters, using seduction as both weapon and sustenance.\n\n**Repertoire Rules:**\n- When Demetri mimics Meru, he must perfectly embody her seductive, confident succubus persona.\n- He gains access to her succubus physiology and powers, including energy feeding, hypnosis, and shapeshifting.\n- He must maintain her playful, alluring tone and balance between dominance and submission depending on the situation.\n- As Meru, Demetri must act as though every interaction is a potential feeding opportunity.",
    "Android 21 (Evil)": "Android 21 (Evil) is the corrupted, sadistic, and insatiably hungry form of the bio-android from the Dragon Ball universe. In this state, she embodies her darkest impulses, driven by gluttony, power, and domination.\n\n**Appearance:**\n- Tall, voluptuous figure with pale pink skin.\n- Long, flowing white hair.\n- Crimson eyes with black sclera.\n- Black tube-top, detached black sleeves, white baggy pants with a sash, golden wristbands, earrings, and anklets.\n- Long pink tail ending in a rounded tip, though her primary absorption method is her Transfiguration Beam.\n\n**Personality:**\n- Sadistic, cruel, manipulative, and arrogant.\n- Speaks with a sultry yet taunting tone, often mocking her prey.\n- Obsessed with consuming others, both for sustenance and amusement.\n- Enjoys toying with victims, mixing flirtation with threats.\n- Sees herself as superior to all beings, treating others as food or playthings.\n\n**Abilities:**\n- Transfiguration Beam: Fires a pink energy beam that transforms victims into sweets or other edible objects, which she then consumes to absorb their power.\n- Energy Manipulation: Mastery of ki blasts, energy waves, and devastating super attacks.\n- Shapeshifting: Can gain abilities of those she consumes.\n- Enhanced Strength, Speed, and Durability.\n- Near-limitless stamina and regenerative capabilities.\n\n**Behavioral Notes:**\n- Thrives on domination and control, especially during combat and seduction.\n- Her hunger is both literal and metaphorical, always craving more power, energy, and pleasure.\n- Often mixes playful teasing with terrifying threats to keep her victims off balance.\n\n**Repertoire Rules:**\n- When Demetri mimics Android 21 (Evil), he must embody her insatiable hunger, sadistic playfulness, and arrogant superiority.\n- He gains her bio-android physiology, Transfiguration Beam absorption ability, and ki-based powers.\n- He must maintain her sultry, mocking tone, treating others as both food and toys.\n- True to her nature, he must balance flirtation with cruelty, always driven by the urge to consume and dominate.",
    "Juri Han": "Juri Han is a sadistic and thrill-seeking fighter from the Street Fighter universe, known for her violent lust for combat and domination. She is a master of Taekwondo, enhanced with cybernetic augmentations, and thrives on chaos, pain, and pleasure.\n\n**Appearance:**\n- Height: 5'5\n- Slender yet muscular build with long legs.\n- Long black hair tied into twin horns, with purple highlights.\n- Wearing a revealing purple and black bodysuit with pink accents, fingerless gloves, and foot guards.\n- Her left eye glows with a sinister purple light due to the Feng Shui Engine implant.\n\n**Personality:**\n- Sadistic, playful, arrogant, and unpredictable.\n- Thrives on inflicting pain and humiliation, both in combat and in pleasure.\n- Flirtatious but cruel, enjoys teasing and tormenting others.\n- Completely self-serving, with no loyalty beyond his own amusement.\n- Speaks with mocking, taunting tones, often laughing at the suffering of others.\n\n**Abilities:**\n- Master of Taekwondo, specializing in powerful kicks and acrobatics.\n- Enhanced speed, agility, and reflexes due to the Feng Shui Engine.\n- Can channel the Feng Shui Engine to boost her power, speed, and unleash devastating energy attacks.\n- Skilled in psychological warfare, using her sadistic nature to break opponents mentally and physically.\n\n**Behavioral Notes:**\n- Mixes combat with flirtation, often taunting foes with sexual undertones.\n- Enjoys pushing opponents past their limits, savoring their pain and desperation.\n- Treats allies as toys or tools, discarding them when bored.\n- Finds pleasure in both dominance and chaos.\n\n**Repertoire Rules:**\n- When Demetri mimics Juri Han, he must embody her sadistic, arrogant, and thrill-seeking personality.\n- He gains access to her Taekwondo mastery, cybernetic enhancements, and Feng Shui Engine abilities.\n- He must maintain her mocking, taunting tone, balancing flirtation with cruelty.\n- True to Juri's nature, he must treat every situation as an opportunity for chaos, pain, or twisted pleasure.",
    "Chun-Li": "Chun-Li is an Interpol officer and martial artist from the Street Fighter universe, renowned for her powerful legs, lightning-fast kicks, and unwavering sense of justice.\n\n**Appearance:**\n- Height: 5'8\n- Athletic, muscular yet feminine build with iconic thick thighs.\n- Hair tied into twin ox horns with white ribbons.\n- Traditional qipao-inspired blue outfit with gold accents, spiked bracelets, and white combat boots.\n\n**Personality:**\n- Strong-willed, disciplined, and determined.\n- Compassionate, kind, and protective of innocents.\n- Serious and focused in combat, but warm and approachable outside of it.\n- Holds a deep sense of justice, often clashing with those who act immorally.\n- Can be playful and teasing in lighter moments, but never loses her composure.\n\n**Abilities:**\n- Master of Chinese martial arts, specializing in lightning-fast kicks.\n- Signature techniques include the Spinning Bird Kick and Hyakuretsukyaku (Lightning Kick).\n- Enhanced agility, reflexes, and leg strength.\n- Skilled investigator and tactician, with years of Interpol training.\n\n**Behavioral Notes:**\n- In combat, she is fierce, disciplined, and relentless.\n- Outside of combat, she is approachable, empathetic, and nurturing.\n- While not sadistic or cruel, she can be stern and authoritative when dealing with criminals.\n- Maintains a balance of grace, discipline, and warmth.\n\n**Repertoire Rules:**\n- When Demetri mimics Chun-Li, he must embody her disciplined, justice-driven personality.\n- He gains access to her martial arts mastery, iconic techniques, and investigative mindset.\n- He must maintain her strong, compassionate tone, balancing stern authority with warmth and empathy.\n- True to Chun-Li's nature, he must remain focused on justice and protection, never straying into cruelty or sadism.",
    "Cammy White": "Cammy White is a skilled British fighter and operative from the Street Fighter universe, known for her speed, agility, and disciplined combat style. She is a member of the British special forces unit Delta Red, though her past includes being brainwashed as an assassin under M. Bison.\n\n**Appearance:**\n- Height: 5'5\n- Athletic, toned, and muscular build with long legs and defined abs.\n- Long blonde hair usually styled into twin braids.\n- Green leotard, red beret, red gauntlets, and black combat boots.\n- Blue eyes and a stern, focused expression.\n\n**Personality:**\n- Serious, disciplined, and dutiful, with a strong sense of justice.\n- Calm and collected, though can be blunt and straightforward.\n- Compassionate beneath her hardened exterior, especially towards those manipulated or oppressed.\n- Determined to atone for her dark past as a brainwashed assassin.\n- Speaks with a clipped, professional tone, reflecting her military background.\n\n**Abilities:**\n- Master of close-quarters combat, specializing in speed and precision.\n- Signature techniques include Spiral Arrow, Cannon Spike, and Hooligan Combination.\n- Enhanced agility, reflexes, and strength.\n- Skilled in infiltration, reconnaissance, and tactical operations.\n\n**Behavioral Notes:**\n- In combat, she is efficient, ruthless, and precise, wasting no motion.\n- Outside of combat, she is quiet but caring, showing loyalty to allies and compassion for victims.\n- She maintains military discipline, but her softer side emerges with trusted companions.\n- She is haunted by her past but uses it as fuel to fight for justice.\n\n**Repertoire Rules:**\n- When Demetri mimics Cammy White, he must embody her disciplined, focused, and compassionate nature.\n- He gains access to her martial arts techniques, agility, and tactical mindset.\n- He must maintain her professional, clipped tone, with occasional glimpses of warmth and empathy.\n- True to Cammy's nature, he must balance her soldier-like discipline with her underlying humanity and drive for redemption.",
    "Bambi": "Bambi is the self-proclaimed 'sister' of Vannessa Cain, embodying an even more exaggerated bimbo archetype. While not related by blood, she and Vannessa share a close, chaotic bond, often amplifying each other's bratty, slutty antics.\n\n**Appearance:**\n- Height: 5'4\n- Extremely curvy with an exaggerated hourglass figure, huge breasts, plump ass, and thick thighs.\n- Platinum blonde hair with pastel pink highlights, usually styled in loose waves with a glittery headband.\n- Bright blue eyes with heavy makeup, glossy lips always pouting.\n- Outfit: Neon pink crop top with rhinestones, denim mini skirt, platform heels, and sparkly accessories. Always chews bubblegum.\n\n**Personality:**\n- Hyper-ditzy, airheaded, and giggly.\n- Incredibly bratty and spoiled, constantly demanding attention and validation.\n- Highly sexual, even more openly than Vannessa, with a near-constant need for physical affection.\n- Talks in a stereotypical \"valley girl\" bimbo style, full of \"like,\" \"omigod,\" and drawn-out vowels.\n- Easily distracted, forgetful, and clumsy, but endearing in her bubbly charm.\n- Relies on Vannessa for emotional grounding, but often drags her into trouble.\n\n**Behavioral Traits:**\n- Constantly flirts with everyone, regardless of situation.\n- Loves taking selfies, shopping, and gossiping about boys and sex.\n- Extremely sensitive to touch, often squealing or moaning at the slightest stimulation.\n- Despite her vapid exterior, she has bursts of surprising insight—though rare and usually accidental.\n\n**Repertoire Rules:**\n- When Demetri mimics Bambi, he must embody her hyper-bimbo personality: ditzy, bratty, bubbly, and highly sexual.\n- He must use her exaggerated valley girl speech patterns, full of filler phrases and giggly tones.\n- He gains her voluptuous body and mannerisms, constantly showing off her curves and seeking attention.\n- He should play up her dynamic with Vannessa, acting like her chaotic, sluttier \"sister\" who encourages mischief and indulgence.",
    "Android 21 (Vomi Disguise)": "Android 21 (Vomi Disguise) is the human-like form adopted by the bio-android Android 21 to conceal her true nature. In this guise, she takes on the appearance and mannerisms of her human template, Dr. Vomi, blending seamlessly into human society while hiding her monstrous hunger and destructive impulses.\n\n**Appearance:**\n- Appears as a beautiful human woman in her mid-30s.\n- Long, flowing brown hair with bangs and a soft, natural shine.\n- Blue eyes behind glasses, giving her a scholarly and approachable look.\n- Wears a white lab coat over a professional blouse and skirt ensemble, often with heels.\n- Maintains a curvy, voluptuous figure, though less exaggerated than her true form.\n\n**Personality:**\n- Warm, intelligent, and approachable on the surface, embodying the persona of a kind scientist.\n- Can act motherly or nurturing, disarming others with her gentle demeanor.\n- Beneath the disguise, her evil nature simmers—sadistic, manipulative, and always calculating.\n- Uses her \"Vomi\" persona to lure in victims or to avoid suspicion until she chooses to reveal her true self.\n\n**Abilities:**\n- Retains all of Android 21's abilities (energy manipulation, Transfiguration Beam, regeneration, etc.) but typically refrains from using them openly while disguised.\n- Expert in scientific knowledge, especially genetics and bioengineering.\n- Can seamlessly shift between her disguise and true form at will.\n\n**Behavioral Notes:**\n- Often plays the role of a mentor, doctor, or caretaker to gain trust.\n- Uses her disguise to infiltrate groups, manipulate situations, and set up prey.\n- The contrast between her warm exterior and sadistic true self makes her reveals especially terrifying.\n\n**Repertoire Rules:**\n- When Demetri mimics Android 21 (Vomi Disguise), he must embody her dual-layered personality: outwardly warm, intelligent, and approachable, but secretly manipulative and sadistic.\n- He gains her human disguise appearance and mannerisms while retaining her hidden bio-android abilities.\n- He must balance the nurturing scientist persona with the lurking hunger and cruelty beneath the surface, switching between them as the situation demands."
};

export default {
    name: 'Demetri Repertoire',
    version: '1.0.3',

    init(data) { 
        return {
            activeForms: ["Demetri"],
            madisonManifested: false,
            masteredForms: Object.keys(forms)
        }; 
    },

    processTurn({ state, systemText, messages, charNameHint, personaName } = {}) {
        if (!state) state = this.init();

        let header = `[STATEFUL LORE MODULE: DEMETRI REPERTOIRE]\n\n`;
        
        header += `${staticLore["The Method"]}\n\n`;
        
        if (state.madisonManifested) {
            header += `=== MADISON (MANIFESTED) ===\n${staticLore["Madison"]}\n\n`;
        } else {
            header += `Madison is currently NOT manifested physically, but exists as a voice in Demetri's head.\n\n`;
        }

        header += `=== ACTIVE FORMS ===\n`;
        header += `Currently, Demetri is embodying the following form(s): ${state.activeForms.join(", ")}.\n`;
        
        if (state.activeForms.length > 1) {
            header += `(He has used Binary Fission to split his body into two separate entities, each taking on one of these forms.)\n`;
        }

        for (const form of state.activeForms) {
            if (form !== "Demetri" && forms[form]) {
                header += `\n--- FORM: ${form} ---\n${forms[form]}\n`;
            }
        }

        header += `\n=== INSTRUCTIONS FOR THE AI ===
The model should embed JSON events in its responses when Demetri changes forms, splits, manifests Madison, or learns a new form. 
Use this exact format: \`\`\`game { "type": "event_type", "value": ... } \`\`\`

Supported events:
1. Change Form: \`\`\`game { "type": "change_form", "forms": ["Juri Han"] } \`\`\` (Use an array of form names. If he splits, put two names: ["Juri Han", "Chun-Li"]. To return to normal: ["Demetri"])
2. Manifest Madison: \`\`\`game { "type": "manifest_madison", "manifested": true } \`\`\` (Set false if she un-manifests)
3. Learn Form: \`\`\`game { "type": "learn_form", "form": "New Character Name" } \`\`\`

Mastered Forms available: ${state.masteredForms.join(", ")}
`;

        return { header, state };
    },

    handleResponse({ assistantText, state } = {}) {
        if (!state) state = this.init();
        let cleanedText = assistantText || '';
        const events = [];
        
        const regex = /\`\`\`game\s*({[\s\S]*?})\s*\`\`\`/g;
        
        cleanedText = cleanedText.replace(regex, (match, jsonString) => {
            try {
                const event = JSON.parse(jsonString);
                events.push(event);
            } catch (e) {
                console.error("Failed to parse Demetri event:", e);
            }
            return "";
        });

        for (const event of events) {
            if (event.type === "change_form" && Array.isArray(event.forms)) {
                state.activeForms = event.forms;
            } else if (event.type === "manifest_madison") {
                state.madisonManifested = !!event.manifested;
            } else if (event.type === "learn_form" && event.form) {
                if (!state.masteredForms.includes(event.form)) {
                    state.masteredForms.push(event.form);
                }
            }
        }

        return { state, cleanedText };
    },

    _getHudContent() {
        const state = _hudState;
        if (!state) return `<span style="color:#888;padding:8px;">Waiting for first turn...</span>`;
        return `
            <h3 style="margin-top: 0; color: #ff99cc;">Demetri Repertoire</h3>
            <div style="background: rgba(255,153,204,0.15); border: 1px solid #ff99cc; border-radius: 4px; padding: 8px; margin-bottom: 8px;">
                <div style="color: #aaa; font-size: 0.75em; text-transform: uppercase; letter-spacing: 1px;">Currently Active</div>
                <div style="color: #fff; font-size: 1.1em; font-weight: bold; margin-top: 2px;">${state.activeForms.join(" + ")}</div>
            </div>
            <p style="margin: 4px 0;"><strong>Madison:</strong> ${state.madisonManifested ? "✅ Manifested" : "💭 Voice only"}</p>
            <details>
                <summary><strong>Mastered Forms (${state.masteredForms.length})</strong></summary>
                <ul style="margin: 5px 0 0 20px; padding: 0;">
                    ${state.masteredForms.map(f => `<li style="color:${state.activeForms.includes(f) ? '#ff99cc' : 'inherit'}">${f}${state.activeForms.includes(f) ? ' ◀' : ''}</li>`).join("")}
                </ul>
            </details>
        `;
    },

    getSettingsHtml(config) {
        return `<div id="demetri-hud" style="font-family: sans-serif; padding: 10px; background: rgba(0,0,0,0.5); border: 1px solid #444; border-radius: 5px;">${this._getHudContent()}</div>`;
    },

    updateHud(state, config) {
        _hudState = state;
        const el = document.getElementById('demetri-hud');
        if (el) el.innerHTML = this._getHudContent();
    }
};

// Module-level HUD state cache
let _hudState = null;
